# Generated by Django 6.0 on 2026-07-04 07:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='Student',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='volunteertrainer',
            old_name='teaching_model',
            new_name='teaching_mode',
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
